### ISSUE TITLE
Add colors to theme: white opacity 15% and black opacity 15%

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/wporg-parent-2021#102]
Used for the top border of the updated local header in Learn sites:

![Screenshot 2023-09-04 at 12 36 16 PM](https://github.com/WordPress/wporg-parent-2021/assets/1017872/2a6d37fc-9dc8-4789-8b4c-89a1f5563380)

**Comment by ryelle** [comment]
In showcase, I added the border as a custom color `#ffffff0a`, rather than creating a new color for this. I was on the fence about whether it's necessary— I'd rather not start adding color+opacity combinations, it could make the palette selector unwieldy. 

<img width="300" alt="Screenshot 2023-09-05 at 9 57 30 AM" src="https://github.com/WordPress/wporg-parent-2021/assets/541093/32cf2422-2d80-4ec3-9fb0-9f4319971200">

@WordPress/meta-design Will these two be the only transparent colors used on the site? I'm not sure if [this color list](https://www.figma.com/file/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library?type=design&node-id=101-4217&mode=design&t=25l4zmdtJqVsAQR3-4) is from the previous redesign iteration. If it is just these two, then I think adding them would be fine.

<img width="679" alt="Screenshot 2023-09-05 at 9 52 49 AM" src="https://github.com/WordPress/wporg-parent-2021/assets/541093/6d538a4d-e74a-45ca-8737-7fde8c212e17">

**Comment by jasmussen** [comment]
> Will these two be the only transparent colors used on the site? I'm not sure if [this color list](https://www.figma.com/file/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library?type=design&node-id=101-4217&mode=design&t=25l4zmdtJqVsAQR3-4) is from the previous redesign iteration. If it is just these two, then I think adding them would be fine.

I think we can decide that, yes.

**Comment by adamwoodnz** [comment]
👍  I'll update this issue and PR to add both 15% opacities
