### ISSUE TITLE
Search box active and focus styles

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/wporg-parent-2021#117]
The focus, active, and focus+active states for the search box is missing.

Focus:

![image](https://github.com/WordPress/wporg-parent-2021/assets/1017872/d00c5eaf-890e-4d9a-b7c0-842f7d176797)

Focus + active, note that this also causes a layout shift:

![image](https://github.com/WordPress/wporg-parent-2021/assets/1017872/20897b12-1802-4826-a545-05498d74175d)

_Originally posted by @adamwoodnz in https://github.com/WordPress/wporg-developer/issues/342#issuecomment-1819790374_

**Comment by ryelle** [comment]
Is this an issue just on specific pages or browsers? I see the focus state just fine when using search here https://developer.wordpress.org/plugins/, for example.

<img width="291" alt="Screenshot 2024-01-04 at 5 24 13 PM" src="https://github.com/WordPress/wporg-parent-2021/assets/541093/57617b14-820d-47d2-a6b5-f150396a68e5">

The state is set on `focus-visible` (which should be true for these cases), but that does mean if you're testing with dev tools, toggling `:focus` won't work.

I do see the layout shift on click, so that's an issue regardless.

**Comment by adamwoodnz** [comment]
I'm not sure how @jasmussen discovered it, so I'm not sure about behaviour for a typical user, but I can repro by long tapping with my trackpad:

![search active](https://github.com/WordPress/wporg-parent-2021/assets/1017872/ba67ce58-bd40-439d-865e-06c38953b945)

And in devtools with active + focus:

![Screenshot 2024-01-05 at 11 43 04 AM](https://github.com/WordPress/wporg-parent-2021/assets/1017872/20253c37-8e91-4d30-bf80-0bfcc2e3acfb)

**Comment by ryelle** [comment]
I must always just test with my keyboard, because you're right, clicking the button doesn't add the outline. Well, switching back to `:focus` for the button should fix that.
