### ISSUE TITLE
Improve the print stylesheet throughout WordPress.org

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-parent-2021#158]
The print styles throughout WordPress.org (the sections powered by this parent theme) are pretty rough. It would be worthwhile to make some subtle improvements, much like https://github.com/WordPress/wporg-news-2021/issues/427

**Comment by ryelle** [comment]
I've added a general print stylesheet for the network. I focused on the About & Download subpages (including release pages, which should cascade to all pages), documentation articles & developer handbook articles, code reference pages, and developer blog articles. I also added some specific styles to main for the w.org homepage and "About" page.

I also added a class, `wporg__hide-on-print`, which can be used to hide elements when printing.

A quick check shows that Five for the Future inherits styles nicely. The showcase & directories do too, but if we need to really support printing these they'll need a little more help.

Forums has a few glitches in printing (thread lists and individual posts), should that be updated too?

There's an extra step to deploy this out to Events since it's on the WordCamp infrastructure, so that's not quite right ATM. I'm following up on that.

Let me know if anything looks off, or if I should iterate on any other sections.

**Comment by ndiego** [comment]
Thanks for all your work on this. The `wporg__hide-on-print` class is great. Then, we can use this in the Editor as needed.

> Forums has a few glitches in printing (thread lists and individual posts), should that be updated too?

I don't think so. I cannot imagine people printing forum threads.

**Comment by ryelle** [comment]
Do you think we can close this issue, or are there any places where the styles still need work?

**Comment by ndiego** [comment]
> Do you think we can close this issue, or are there any places where the styles still need work?

I did some spot checks and it looks really good, thanks @ryelle. I'll close this out, and if any other isolated issues pop up, we can address them separately.
