### ISSUE TITLE
Heading with Arrow: Arrow area should be a clickable part of link

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-parent-2021#40]
Initially reported here: https://meta.trac.wordpress.org/ticket/6447

When this pattern is used, only the text is clickable despite the arrow appearing to be part of the link.

![680FC577-373E-4CE4-9ED6-DF426D98700B](https://user-images.githubusercontent.com/541093/185692302-6286bb27-3920-4c07-905c-70342288be3c.jpeg)

Maybe we _should_ assume that a heading using this pattern will always have a link, and add the arrow on `a`.

**Comment by jb510** [comment]
As I see it the issue here is
.is-style-with-arrow::after is applying the CSS arrow to the H2 with that class, not the anchor itself.  
.is-style-with-arrow a::after would fix this, but that arrow border CSS is kind complicated (perhaps overly so) so it'll take a bit more hacking to keep it looking the way it is now.

**Comment by adamwoodnz** [comment]
> Maybe we should assume that a heading using this pattern will always have a link, and add the arrow on a.

This seems appropriate to me, given that adding this arrow treatment suggests a link should be present.

I'll start work based on that assumption.

**Comment by adamwoodnz** [comment]
Reopening to add editor fix for Firefox
